
[font]

normal = { family = "JetBrainsMono Nerd Font", style = "Regular" }
bold = { family = "JetBrainsMono Nerd Font", style = "Bold" }
italic = { family = "JetBrainsMono Nerd Font", style = "Italic" }
bold_italic = { family = "JetBrainsMono Nerd Font", style = "Bold Italic" }
 
size = 12.0

[env]
TERM = "xterm-256color"

[general]
import = [
    "~/.config/alacritty/themes/themes/monokai_charcoal.toml"
]

